language: minimal

stages:
  - before_install
  - install
  - before_script
  - script
  - after_success
  - name: deploy
    if: branch = master

addons:
  apt:
    packages:
      - tree

# Cache all the generated files between stages (and builds)
cache:
  directories:
    - build

# Skip any language defaults
install: skip

# Skip any language defaults
script: skip

jobs:
  include:
    # Golang
    - stage: before_install
      name: "Go: Clean out cache"
      language: go
      go: "1.10"
      before_install:
        - tree build
        - rm -rf build

    - stage: install
      name: "Go: Install protoc compiler"
      language: go
      go: "1.10"
      install:
        - mkdir -p build/protoc
        - pushd build/protoc
        - wget https://github.com/google/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip
        - unzip -u protoc*.zip
        - export PATH=$PATH:$PWD/bin
        - popd
        - tree build/protoc/

    - stage: before_script
      name: "Go: Fetch gRPC protoc plugin"
      language: go
      go: "1.10"
      before_script:
        - go get -u github.com/golang/protobuf/protoc-gen-go
        - export PATH=$PATH:$GOPATH/bin

    - stage: script
      name: "Go: Generate sources"
      language: go
      go: "1.10"
      script:
        - tree build
        - tree $GOPATH
        - mkdir -p build/go
        - which protoc
        - echo "$TRAVIS_BUILD_NUMBER" >> build/go/generated.txt
        - tree build/go

    - stage: deploy
      name: "Go: Deploy generated sources back to repo"
      deploy:
        provider: pages
        local-dir: build/go/
        target-branch: go1
        keep-history: true
        github-token: $GITHUB_TOKEN
        verbose: true

    # C# & .NET
    - stage: before_install
      name: "C#: Clean out cache"
      language: csharp
      mono: none
      dotnet: 2.0
      before_install:
        - tree build
        - rm -rf build

    - stage: install
      name: "C#: Fetch gRPC protoc plugin"
      language: csharp
      mono: none
      dotnet: 2.0
      install:
        - mkdir -p build/csharp_project
        - pushd build/csharp_project
        - dotnet new console
        - env NUGET_PACKAGES=$PWD/packages dotnet add package grpc.tools
        - popd

    - stage: script
      name: "C#: Generate sources"
      language: csharp
      mono: none
      dotnet: 2.0
      script:
        - tree build
        - tree $GOPATH
        - mkdir -p build/csharp
        - which protoc
        - ls -la build/csharp_project/packages/grpc.tools/*/tools/linux_x64/
        - echo "$TRAVIS_BUILD_NUMBER" >> build/csharp/generated.txt
        - tree build/csharp

    - stage: after_success
      name: "C#: Build .NET nupkg"
      language: csharp
      mono: none
      dotnet: 2.0
      after_success:
        - touch build/csharp/gen.$TRAVIS_BUILD_NUMBER.nupkg

    - stage: deploy
      name: "C#: Deploy generated sources back to repo"
      deploy:
        provider: pages
        local-dir: build/csharp/
        target-branch: csharp
        keep-history: true
        github-token: $GITHUB_TOKEN
        verbose: true

    # Python
    - stage: before_install
      name: "Python: Clean out cache"
      language: python
      python: "3.6"
      before_install:
        - tree build
        - rm -rf build

    - stage: script
      name: "Python: Generate sources"
      language: python
      python: "3.6"
      script:
        - tree build
        - mkdir -p build/python
        - echo "$TRAVIS_BUILD_NUMBER" >> build/python/generated.txt
        - tree build/python

    - stage: after_success
      name: "Python: Build wheel pkg"
      language: python
      python: "3.6"
      after_success:
        - touch build/python/gen.$TRAVIS_BUILD_NUMBER.whl

      # Deploy Python generated sources back to repo
      # Deploy .NET nupkg to NuGet
      # Deploy wheel to PyPi

