language: minimal

stages:
  - generate
  - package
  - name: deploy
    if: branch = master

addons:
  apt:
    packages:
      - tree

# Cache all the generated files between stages (and builds)
cache:
  directories:
    - build

# Clean out the cache (since we only want it between stages)
before_cache:
  - rm -f build

before_install:
  - mkdir -p protoc build/go build/csharp build/python

install:
  - pushd protoc
  - wget https://github.com/google/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip
  - unzip protoc*.zip
  - export PATH=$PATH:$PWD/bin/
  - popd

jobs:
  include:
    - stage: generate
      name: "Generate Go sources"
      language: go
      go: "1.10"
      script:
        - echo "$TRAVIS_BUILD_NUMBER" >> build/go/generated.txt

    - stage: generate
      name: "Generate C# sources"
      language: csharp
      script:
        - echo "$TRAVIS_BUILD_NUMBER" >> build/csharp/generated.txt

    - stage: generate
      name: "Generate Python sources"
      language: python
      python: "3.6"
      script:
        - echo "$TRAVIS_BUILD_NUMBER" >> build/python/generated.txt

    - stage: generate
      name: "List all generated files"
      script:
        - tree build

    - stage: package
      name: "Build .NET nupkg from C# sources"
      language: csharp
      script:
        - touch build/csharp/gen.$TRAVIS_BUILD_NUMBER.nupkg

    - stage: package
      name: "Build wheel pkg from Python sources"
      language: python
      python: "3.6"
      script:
        - touch build/python/gen.$TRAVIS_BUILD_NUMBER.whl

    - stage: deploy
      name: "Deploy Go generated sources back to repo"
      provider: pages
      local-dir: build/go/
      target-branch: go1
      keep-history: true
      github-token: $GITHUB_TOKEN
      skip-cleanup: true
      verbose: true

    - stage: deploy
      name: "Deploy C# generated sources back to repo"
      provider: pages
      local-dir: build/csharp/
      target-branch: csharp
      keep-history: true
      github-token: $GITHUB_TOKEN
      skip-cleanup: true
      verbose: true

      # Deploy Python generated sources back to repo
      # Deploy .NET nupkg to NuGet
      # Deploy wheel to PyPi

