language: minimal

env:
  global:
    - SRC=build/

    - PROTOC=https://github.com/google/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip
    - PROTOC_SRC=build/protoc/

    - GO_SRC=build/go/
    - GO_BRANCH=go1
    - GO_VERSION="1.10"

    - CSHARP_SRC=build/csharp/
    - CSHARP_BRANCH=csharp

    - PYTHON_SRC=build/python/
    - PYTHON_BRANCH=python
    - PYTHON_VERSION="3.6"

stages:
  - generate
  - package
  - name: deploy
    if: branch = master

addons:
  apt:
    packages:
      - tree

# Cache all the generated files between stages (and builds)
cache:
  directories:
    - $SRC

# Clean out the cache (since we only want it between stages)
before_cache:
  - rm -f $SRC

before_install:
  - mkdir -p $PROTOC_SRC
  - mkdir -p $GO_SRC
  - mkdir -p $CSHARP_SRC
  - mkdir -p $PYTHON_SRC
  - tree .

install:
  - mkdir -p $PROTOC_SRC
  - pushd $PROTOC_SRC
  - wget $PROTOC
  - unzip protoc*.zip
  - export PATH=$PATH:$PWD/bin/
  - popd

jobs:
  include:
    - stage: generate
      name: "Generate Go sources"
      language: go
      go: $GO_VERSION
      script:
        - echo "$TRAVIS_BUILD_NUMBER" >> $GO_SRC/generated.txt

    - stage: generate
      name: "Generate C# sources"
      language: csharp
      script:
        - echo "$TRAVIS_BUILD_NUMBER" >> $CSHARP_SRC/generated.txt

    - stage: generate
      name: "Generate Python sources"
      language: python
      python: $PYTHON_VERSION
      script:
        - echo "$TRAVIS_BUILD_NUMBER" >> $PYTHON_SRC/generated.txt

    - stage: generate
      name: "List all generated files"
      script:
        - tree $SRC

    - stage: package
      name: "Build .NET nupkg from C# sources"
      language: csharp
      script:
        - touch $CSHARP_SRC/gen.$TRAVIS_BUILD_NUMBER.nupkg

    - stage: package
      name: "Build wheel pkg from Python sources"
      language: python
      python: $PYTHON_VERSION
      script:
        - touch $PYTHON_SRC/gen.$TRAVIS_BUILD_NUMBER.whl

    - stage: deploy
      name: "Deploy Go generated sources back to repo"
      provider: pages
      local-dir: $GO_SRC
      target-branch: $GO_BRANCH
      keep-history: true
      github-token: $GITHUB_TOKEN
      skip-cleanup: true
      verbose: true

    - stage: deploy
      name: "Deploy C# generated sources back to repo"
      provider: pages
      local-dir: $CSHARP_SRC
      target-branch: $CSHARP_BRANCH
      keep-history: true
      github-token: $GITHUB_TOKEN
      skip-cleanup: true
      verbose: true

      # Deploy Python generated sources back to repo
      # Deploy .NET nupkg to NuGet
      # Deploy wheel to PyPi

